
title: My Resume
url: 'http://resume.uuma.cc'
baseurl: '/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Chang Yanhui
tagline: Quality Control Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: me@uuma.cc
phone: 155 1019 2745
website: resume@uuma.cc #do not add http://
linkedin: changyanhui
github: changyanhui
twitter: '@changyanhui'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
